# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Iterable as typing___Iterable,
    Optional as typing___Optional,
    Text as typing___Text,
    Union as typing___Union,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int
if sys.version_info < (3,):
    builtin___buffer = buffer
    builtin___unicode = unicode


DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

class Request(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    sentence: typing___Text = ...

    def __init__(self,
        *,
        sentence : typing___Optional[typing___Text] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> Request: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> Request: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"sentence",b"sentence"]) -> None: ...
type___Request = Request

class Token(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    text: typing___Text = ...
    tag: typing___Text = ...
    lemma: typing___Text = ...
    entity: typing___Text = ...
    index: builtin___int = ...
    length: builtin___int = ...

    def __init__(self,
        *,
        text : typing___Optional[typing___Text] = None,
        tag : typing___Optional[typing___Text] = None,
        lemma : typing___Optional[typing___Text] = None,
        entity : typing___Optional[typing___Text] = None,
        index : typing___Optional[builtin___int] = None,
        length : typing___Optional[builtin___int] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> Token: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> Token: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"entity",b"entity",u"index",b"index",u"lemma",b"lemma",u"length",b"length",u"tag",b"tag",u"text",b"text"]) -> None: ...
type___Token = Token

class Reply(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def tokens(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___Token]: ...

    def __init__(self,
        *,
        tokens : typing___Optional[typing___Iterable[type___Token]] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> Reply: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> Reply: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"tokens",b"tokens"]) -> None: ...
type___Reply = Reply
